export const API_URL = "https://fakestoreapi.com/products"
// export const MY_API_URL = "http://localhost:9999/items"
export const MY_API_URL = "https://api-3-bik5.onrender.com/items"
// export const SELLER_API_URL = "http://localhost:9999/sellers"
export const SELLER_API_URL = "https://api-3-bik5.onrender.com/sellers"
// export const USER_API_URL = "http://localhost:9999/users"
export const USER_API_URL = "https://api-3-bik5.onrender.com/users"
// export const ADDRESS_API_URL = "http://localhost:9999/address"
export const ADDRESS_API_URL = "https://api-3-bik5.onrender.com/address"

export const BASE_URL = "https://api-3-bik5.onrender.com/"
// export const BASE_URL = "http://localhost:9999/"