export const API_URL = "https://fakestoreapi.com/products"
// export const MY_API_URL = "http://localhost:9999/items"
 export const MY_API_URL = "https://api-3-bik5.onrender.com/items"
//export const SELLER_API_URL = "http://localhost:9999/sellers"
export const SELLER_API_URL = "https://api-3-bik5.onrender.com/sellers"
